post_install() {
    mhwd-gpu --check
    cat <<'EOF'

>>> You must tell Xorg to use the nvidia driver with kernels >=5.11.0.
    You must also set IgnoreABI option with Xorg version >= 21.1.1.
    Minimal config example provided in /usr/share/nvidia-340xx/20-nvidia.conf
    which you should manually place in /etc/X11/xorg.conf.d/

EOF
}

post_upgrade() {
    post_install
}

post_remove() {
    mhwd-gpu --check
}